name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            chrome_install_cmd: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo dpkg -i google-chrome-stable_current_amd64.deb
            chromium_install_cmd: sudo apt-get install chromium-browser
            brave_install_cmd: |
                                'curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
                                echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
                                sudo apt update
                                sudo apt install brave-browser'
          - os: macos-latest
            chrome_install_cmd: brew install --cask google-chrome
            chromium_install_cmd: brew install --cask chromium
            brave_install_cmd: echo "Homebrew brave-browser cask is broken"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Chrome
        run: ${{ matrix.chrome_install_cmd }}
        
      - name: Install Chromium
        run: ${{ matrix.chromium_install_cmd }}
      
      - name: Install Brave
        run: ${{ matrix.brave_install_cmd }}

      - name: Check for browsers
        run: |
          echo "Chrome: $(which google-chrome)"
          echo "Chromium: $(which chromium-browser)"
          echo "Brave: $(which brave-browser)"
          echo "Firefox: $(which firefox)"
